name: Build Aseprite for Windows x64

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tag:
        description: 'Aseprite tag or branch to build'
        required: false
        default: 'main'

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Aseprite source
        uses: actions/checkout@v2
        with:
          repository: aseprite/aseprite
          ref: ${{ github.event.inputs.tag }}
          path: aseprite

      - name: Checkout builder repo
        uses: actions/checkout@v2
        with:
          path: builder

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: |
          choco install -y ninja
          choco install -y cmake --installargs 'ADD_CMAKE_TO_PATH=System'
          choco install -y git

      - name: Download and build Skia
        working-directory: aseprite
        run: |
          # Fetch the latest get_skia.bat from the correct branch
          curl -fsSL -o get_skia.bat https://raw.githubusercontent.com/aseprite/aseprite/${{ github.event.inputs.tag || 'main' }}/third_party/get_skia.bat
          if not exist get_skia.bat (
            echo "Failed to download get_skia.bat. Check the URL and branch/tag."
            exit /b 1
          )
          # Run the Skia build script
          cmd /c get_skia.bat

      - name: Set SKIA_DIR environment variable
        run: echo "SKIA_DIR=${{ github.workspace }}\\aseprite\\third_party\\skia" >> $GITHUB_ENV

      - name: Create build directory
        run: mkdir build
        working-directory: aseprite

      - name: Configure the project with CMake
        working-directory: aseprite/build
        run: >
          cmake -DCMAKE_BUILD_TYPE=Release
          -DLAF_BACKEND=skia
          -DSKIA_DIR="${{ env.SKIA_DIR }}"
          -G "Ninja" ..

      - name: Build Aseprite
        working-directory: aseprite/build
        run: ninja aseprite

      - name: Package Aseprite
        working-directory: aseprite/build/bin
        run: |
          Compress-Archive -LiteralPath aseprite.exe, data -DestinationPath aseprite-windows-x64.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-windows-x64
          path: aseprite/build/bin/aseprite-windows-x64.zip
